blog/urls.py
from django.urls import path, re_path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
	# path('', views.post_list, name='post_list'),
	path('', views.PostListView.as_view(), name='post_list'),
	re_path(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
	# path('<int:year>/<int:month>/<int:day>/<str:post>/', views.post_detail, name='post_detail'),
	re_path(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]{1,2})/(?P<post>[-\w]+)/$', views.post_detail,
																								 name='post_detail'),
	path('<int:post_id>/share/', views.post_share, name='post_share'),
	path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
	path('feed/', LatestPostsFeed(), name='post_feed'),
	path('search/', views.post_search, name='post_search'),

]

# r'^post/(?P<slug>[-\w]+)/$'

python6th_catalogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class PublishedManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
	class Status(models.TextChoices):
		DRAFT = 'DF', 'Draft'
		PUBLISHED = 'PB', 'Published'

	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='publish', allow_unicode=True)
	author = models.ForeignKey(User, on_delete=CASCADE, related_name='blog_posts')
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)  # default=timezone.now
	created = models.DateTimeField(auto_now_add=True)
	update = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

	objects = models.Manager()  # 디폴트 매니저
	published = PublishedManager()  # 사용자 정의 매니저
	tags = TaggableManager()  # 테그

	class Meta:
		ordering = ['-publish']
		indexes = [
			models.Index(fields=['-publish']),
		]

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse(
			'blog:post_detail',
			args=[
				self.publish.year,
				self.publish.month,
				self.publish.day,
				self.slug
			]
		)


# 댓글 모델
class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	update = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	class Meta:
		ordering = ['created']
		indexes = [
			models.Index(fields=['created']),
		]

	def __str__(self):
		return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
	query = forms.CharField()

blog/views.py
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery, TrigramSimilarity
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag
from django.db.models import Count

from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post


# Create your views here.

class PostListView(ListView):
	queryset = Post.published.all()
	context_object_name = 'posts'
	paginate_by = 5
	template_name = 'blog/post/list.html'
	ordering = '-created'


def post_list(request, tag_slug=None):
	post_list = Post.published.all()

	tag = None
	# 테그 슬러그가 있는 경우
	if tag_slug:
		# Tag객체 가져옴
		tag = get_object_or_404(Tag, slug=tag_slug)
		post_list = post_list.filter(tags__in=[tag])

	# 페이지당 3개의 게시물로
	paginator = Paginator(post_list, 5)
	page_number = request.GET.get('page', 1)
	try:
		posts = paginator.page(page_number)
	except EmptyPage:
		# page_number가 범위를 벗어난 경우 결과릐 마지막 페이지 제공
		posts = paginator.page(paginator.num_pages)
	except PageNotAnInteger:
		# page_number가 정수가 아닌 경우 첫번째 페이지 제공
		posts = paginator.page(1)

	return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
	post = get_object_or_404(
		Post,
		status=Post.Status.PUBLISHED,
		slug=post,
		publish__year=year,
		publish__month=month,
		publish__day=day,
	)
	# 해당 포스트글에 대한 모든 활성 댓글들 가져오기 위한 쿼리셋 추가 related_name속성을 사용함
	comments = post.comments.filter(active=True).order_by('-created')
	# 댓글폼 인스턴스 생성
	form = CommentForm()

	# similar posts 리스트
	post_tags_ids = post.tags.values_list('id', flat=True)
	similar_posts = Post.published.filter(tags__in=post_tags_ids)\
								  .exclude(id=post.id) \
								  .annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
	# similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
	# 그냥 이어서 써도 됨

	return render(request, 'blog/post/detail.html', {'post': post,
													 'comments': comments,
													 'form': form,
													 'similar_posts': similar_posts})


def post_share(request, post_id):
	# id로 글 검색
	post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
	sent = False
	if request.method == 'POST':
		# 폼이 제출되었음
		form = EmailPostForm(request.POST)
		if form.is_valid():
			# 폼 필드 유효한지 검사후
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = f"{cd['name']} 님이 {post.title}을(를) 추천합니다."
			message = f"{post.title}을(를) {post_url}에서 읽어보세요.\n\n" \
					  f"{cd['name']}의 의견 : {cd['comments']}"
			send_mail(subject, message, 'jklo0220@gmail.com', [cd['to']])

			# sent = True
		print(post.get_absolute_url())
		return redirect(post.get_absolute_url())
	else:
		form = EmailPostForm()
	return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


# 댓글 뷰 (request POST 만 받음)
@require_POST
def post_comment(request, post_id):
	post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
	comment = None
	form = CommentForm(data=request.POST)
	if form.is_valid():
		# commit=False를 사용하면 db에 저장하지 않고 Comment객체를 생성함
		comment = form.save(commit=False)
		# 댓글에 게시물 할당
		comment.post = post
		# DB저장
		comment.save()
	return render(
		request,
		'blog/post/comment.html',
		{'post': post,
		 'form': form,
		 'comment': comment
		 }
	)


# 검색 뷰
def post_search(request):
	form = SearchForm()
	query = None
	results = []
	if 'query' in request.GET:
		form = SearchForm(request.GET)
		if form.is_valid():
			query = form.cleaned_data['query']
			results = Post.published.annotate(
				similarity=TrigramSimilarity('title', query),
			).filter(similarity__gt=0.3).order_by('-similarity')
			# search_vector = SearchVector('title', 'tags__name', weight='A') + \
			# 				SearchVector('body', weight='B')
			# search_query = SearchQuery(query)
			# results = Post.published.annotate(
			# 	search=search_vector,
			# 	rank=SearchRank(search_vector, search_query)
			# ).filter(rank__gte=0.3).order_by('-rank')
	return render(request,
				  'blog/post/search.html',
				  {'form': form,
				   'query': query,
				   'results': results})

templates/blog/base.html
{% load static %}
{% load blog_tags %}

<!doctype html>
<html lang="ko">

{% include 'blog/head.html' %}

<body>

<div id="content">
    {% block content %}
    {% endblock content %}
</div>
<div id="sidebar">
    <h2>My blog</h2>
    <p>
        This is my blog.
        I've written {% total_posts %} posts so far.
    </p>

    <!-- RSS Feed -->
    <p>
        <a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a>
    </p>

    <!-- 최근 포스트 -->
    <h3>Latest posts</h3>
    {% show_latest_posts 3 %}

    <!-- 댓글가장 많은 포스트 -->
    <h3>Most commented posts</h3>
    {% get_most_commented_posts 3 as most_commented_posts %}
    <ul>
        {% for most_commented_post in most_commented_posts %}
            <li>
                <a href="{{ most_commented_post.get_absolute_url }}">{{ most_commented_post.title }}</a>
            </li>
        {% endfor %}
    </ul>

    <!-- 목록으로 돌아가기 -->
    <p>
        <a href="{% url 'blog:post_list' %}">Back to List</a>
    </p>
    <!-- 검색창 -->
    <p>
        <a href="{% url 'blog:post_search' %}">Search</a>
    </p>
</div>



<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바 스크립트 추가 블럭 -->
{% block script %}
{% endblock script %}

</body>
</html>

templates/blog/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <!-- blog CSS -->
    <link rel="stylesheet" href="{% static 'blog.css' %}">

    <title>Catalog App</title>
</head>

templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block content %}

    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock content%}

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block content %}

    <h1>{{ post.title }}</h1>

    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>

    <hr>

    <!-- 유사한 포스트 목록 -->
    <h4>Similar posts</h4> |
    {% for similar_post in similar_posts %}

             <a href="{{ similar_post.get_absolute_url }}">{{ similar_post.title }}</a> |

    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    <hr>

    <!-- 댓글 총 갯수 -->
    {% with comments.count as total_comments %}
        <h4>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h4>
    {% endwith %}

    <!-- 댓글 출력 -->
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
        <p>There are no comments.</p>
    {% endfor %}

    <hr>

    <!-- 댓글 입력 폼 -->
    {% include "blog/post/includes/comment_form.html" %}

{% endblock content%}

templates/blog/post/includes/comment_form.html
<h4>Add a new comment</h4>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Add comment"></p>
</form>

templates/blog/post/latest_posts.html
<ul>
    {% for latest_post in latest_posts %}
        <li>
            <a href="{{ latest_post.get_absolute_url }}">{{ latest_post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block content %}
    <h1>My blog</h1>
    <!-- 테그 있다면 출력 -->
    {% if tag %}
        <h2> Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <!-- post 제목 -->
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <!-- 태그 -->
        <p class="tags" style="font-size: small">
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    #{{ tag.name }}
                </a>
                {% if not forloop.last %} , {% endif %}
            {% endfor %}

        </p>

        <!-- 작성자, 작성일 -->
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>

        <!-- 본문요약 -->
        {{ post.body|markdown|truncatewords:30 }}
    {% endfor %}

    <!-- 페이징 -->
    {% include "pagination.html" with page=page_obj %}

{% endblock content %}

templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block content %}

    {% if query %}
        <h2>Posts containing "{{ query }}"</h2>
        <h4>
            {% with results.count as total_results %}
                Founf {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h4>
        {% for result in results %}
            <h4>
                <a href="{{ result.get_absolute_url }}">{{ result.title }}</a>
            </h4>
            {{ result.body|markdown|truncatewords_html:12 }}
            {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Search again</a></p>

    {% else %}
        <h2>Search for posts</h2>
        <form method="get">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}

{% endblock content%}

templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block content %}

    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}

{% endblock content %}

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <!-- blog CSS -->
    <link rel="stylesheet" href="{% static blog.css %}">

    <title>Catalog App</title>
</head>

templates/pagination.html
<div class="pagination">
    <span class="step-link">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            {% for page_number in page.paginator.page_range %}
                {% if page_number >= page.number|add:-3 and page_number <= page.number|add:3 %}
                        <a href="?page={{ page_number }}" class=" active">{{ page_number }}</a>
                {% endif %}
            {% endfor %}

{#            Page {{ page.number }} of {{ page.paginator.num_pages }}.#}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>